  before_install: 
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive

script:
  - make all

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build   
    on:
      branch: main

  # make a release on github
  # TODO: edit the file list to specify what should be released
  #
  # - provider: releases
  #   skip_cleanup: true
  #   api_key: $github_token
  #   file:
  #     - path/to/file  
  #     - second/path/to/file
  #   on:
  #     tags: true  