# means always run builds on Ubuntu Bionic 18.04
dist: bionic  

cache:
  directories:
    - /usr/share/texlive
    - /usr/bin/pandoc
  
before_install:
  - chmod 755 /usr/share/texlive
  - chmod 755 /usr/bin/pandoc
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive-full

script:
  - make all

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build   
    on:
      branch: main

  # make a release on github
  # TODO: edit the file list to specify what should be released
  #
  # - provider: releases
  #   skip_cleanup: true
  #   api_key: $github_token
  #   file:
  #     - path/to/file  
  #     - second/path/to/file
  #   on:
  #     tags: true  