language: bash

dist: bionic

before_install: 
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive
  - sudo apt-get install -y lmodern
  - sudo python3 get-pip.py
  - python3 -m pip3 install Pygments
  - python3 -m pip3 install pandoc-include

script:
  - make all

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build   
    on:
      branch: main
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file:
      - build/CS1301.pdf
      - build/CS1301.odt
    on:
      tags: true  