dist: "focal"

language: python

python:
  - "3.7"

before_install: 
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive
  - sudo apt-get install -y texlive-latex-extra
  - sudo apt-get install -y lmodern 
  - pip install Pygments
  # - pip install pandoc-include

script:
  - make all

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build   
    on:
      branch: main
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file:
      - build/book.pdf
      - build/book.odt
    on:
      tags: true  