dist: "focal"

language: python

python:
  - "3.7"

install: 
  # pandoc v2.13
  - wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb && sudo dpkg -i pandoc-2.13-1-amd64.deb
  # LaTeX
  - sudo apt-get install -y texlive
  # needed to use XeLatex pandoc option
  - sudo apt-get install -y texlive-xetex
  # resolves LaTeX Error: `letltxmacro.sty' not found
  - sudo apt-get install -y texlive-latex-extra
  # resolves another LaTeX .sty error
  - sudo apt-get install -y lmodern 
  # needed for code highlighting
  - pip install Pygments
  # needed for including other files within markdown
  - pip install pandoc-include

script:
  - make all

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build   
    on:
      branch: main
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file:
      # list of files to include in release package
      - build/book.html
      - build/book.pdf
      - build/book.odt
    on:
      tags: true  