dist: bionic  # specify build env, ubuntu 18.04 (Bionic Beaver)

# cache:
#   # TODO: try to cache the apt-get stuff, esp. texlive
#   # challenge is caching these arbitrary dirs
#   # https://stackoverflow.com/q/47603077/4054683
#   # https://docs.travis-ci.com/user/caching#arbitrary-directories
#   directories:
#     - pandoc  ??? where dot hese install by default?
#     - texlive ??? 
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive-full 
  - kpsewhich latex.ltx
  - kpsewhich pandoc

script:
  - make all

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build   
    on:
      branch: main

  # make a release on github
  # TODO: edit the file list to specify what should be released
  #
  # - provider: releases
  #   skip_cleanup: true
  #   api_key: $github_token
  #   file:
  #     - path/to/file  
  #     - second/path/to/file
  #   on:
  #     tags: true  