name: build

#  specify when this workflow should run
on:
  # on every push to main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup pandoc in the env
    - uses: docker://pandoc/core:2.9
      # with:
      #   args: "--help"    
      
      # we can appended additional flags to pandoc command
      # see more examples: https://github.com/pandoc/pandoc-action-example 

    # checkout main
    - uses: actions/checkout@main
      with:
        fetch-depth: 1  

    # run something within the configured env 
    - name: build
      run: make build  

    # Deploy build artifacts or docs to pages
    # https://github.com/marketplace/actions/deploy-to-github-pages
    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@4.1.2
    #   with:
    #     branch: gh-pages # The branch the action should deploy to.
    #     folder: build # The folder the action should deploy.